### ISSUE TITLE
Issue with registering a new user.

### ISSUE THREAD

**Issue by blimey85** [bloggervista/Bee-Connect#29]
I cloned your repo, set it up, started the server, redis, and sidekiq. I then went to register and it gave an error saying to look below for the actual errors but nothing else was showing. I traced that back on the command line to an issue with the role not being present. Some more digging led me to a possible fix by changing line 2 in user.rb to `before_validation :set_default_role`. What's happening is that it wants the role to exist when the validation happens. By changing the callback to a `before_validation` it happens and then the validations pass. I'll do a PR if this is agreeable.

Second thing, I can't login as an admin and I'm not sure why. From what I can tell, I need to login to the main site as the admin user, then switch to the admin url, and I should get the admin dashboard. However, when trying to login as admin to the main site, I get `Completed 401 Unauthorized in 22ms (ActiveRecord: 4.2ms)`.

Third thing, right now the repo is hard coded to use Gmail as an smtp server, even in develop, and that fails. Thus the error log gets spammed with Sidekiq failures. There's a couple of gems available for handling emails in dev. Mailcatcher and LetterOpener are two of them. I typically use Mailcatcher because it's separate from my project and I just leave it running and all of my projects can hit it.

Lastly, how is this project managed? Is there a roadmap? Is anyone actively working on it currently? I know two things are getting it running Rails 5.2 so it's current, and updating to Bootstrap 4.

**Comment by bloggervista** [comment]
@blimey85  Thank you .

PR are welcome and will be accepted. I used to main this project in cloud9 but after it required paid membership and due to financial problem I stopped using it .

Here is the roadmap of this project

https://github.com/bloggervista/Bee-Connect#future-of-this-project

Currently I am on windows and planning to buy mac after having money and will upgrade to rails 5.2 and bootstrap 4. 

Currently I am only maintaining it . If somebody want to maintain it I am happy to collaborate . For that please send email to bloggervista@gmail.com

And I want to write tests for it also but let see :)

**Comment by bloggervista** [comment]
If any problem feel free to reopen issue.
